import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { UUID } from '../models/core';
import type { CorrectiveAction } from './correctiveActionsService';
import { downloadPdfReport, drawPdfCoverWithLogo } from './reportExportService';
import { fetchUserDisplayNameMap } from './userDisplayNameService';

function formatDate(iso: string | null | undefined): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toLocaleDateString('en-ZA');
}

export async function exportCapaListPdf(input: {
  capas: CorrectiveAction[];
  companyId?: UUID;
  companyName: string;
  generatedBy: string;
  logoUrl?: string | null;
  filename?: string;
}): Promise<void> {
  const safeOrg = input.companyName.replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'safecloudafrica';
  const filename = input.filename ?? `${safeOrg}-capa-${new Date().toISOString().slice(0, 10)}.pdf`;
  const metaLines = [
    `Company: ${input.companyName}`,
    `Generated by: ${input.generatedBy}`,
    `Generated at: ${new Date().toISOString()}`,
    `Records: ${input.capas.length}`
  ];

  const nameMap = input.companyId
    ? await fetchUserDisplayNameMap(
        input.companyId,
        input.capas.map((capa) => capa.assigned_to_user_id)
      )
    : new Map<string, string>();

  const rows = input.capas.map((capa) => ({
    action_number: capa.action_number,
    title: capa.title,
    status: capa.status,
    priority: capa.priority,
    action_type: capa.action_type,
    source_type: capa.source_type,
    due_date: capa.due_date ?? '',
    assigned_to: capa.assigned_to_user_id
      ? nameMap.get(String(capa.assigned_to_user_id)) ?? capa.assigned_to_user_id
      : '',
    completed_date: capa.completed_date ?? ''
  }));

  await downloadPdfReport(
    filename,
    `${input.companyName} — CAPA Register`,
    rows,
    metaLines,
    { headerColor: [30, 64, 175], logoUrl: input.logoUrl }
  );
}

export async function exportCapaDetailPdf(input: {
  capa: CorrectiveAction;
  companyName: string;
  generatedBy: string;
  logoUrl?: string | null;
}): Promise<Blob> {
  const { capa } = input;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  let y = await drawPdfCoverWithLogo(doc, {
    title: 'Corrective Action (CAPA)',
    subtitle: `${capa.action_number} — ${capa.title}`,
    companyName: input.companyName,
    generatedBy: input.generatedBy,
    logoUrl: input.logoUrl
  });

  const detailRows: Array<[string, string]> = [
    ['Action number', capa.action_number],
    ['Status', capa.status],
    ['Priority', capa.priority],
    ['Action type', capa.action_type],
    ['Source type', capa.source_type],
    ['Due date', formatDate(capa.due_date)],
    ['Completed date', formatDate(capa.completed_date)],
    ['Verified date', formatDate(capa.verified_date)],
    ['Root cause', capa.root_cause ?? '—'],
    ['Proposed solution', capa.proposed_solution ?? '—'],
    ['Effectiveness check', capa.effectiveness_check ?? '—']
  ];

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('CAPA details', 40, y);
  y += 16;

  autoTable(doc, {
    startY: y,
    body: detailRows,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 4, overflow: 'linebreak' },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 130 },
      1: { cellWidth: pageWidth - 210 }
    }
  });

  let nextY = ((doc as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? y) + 20;
  if (capa.description?.trim()) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Description', 40, nextY);
    nextY += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(capa.description.trim(), pageWidth - 80);
    doc.text(lines, 40, nextY);
  }

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - 80, doc.internal.pageSize.getHeight() - 20);
  }

  return doc.output('blob');
}
