import ExcelJS from 'exceljs';

/**
 * Shared styled-Excel-workbook builder, used by every "Export Excel" button
 * that replaced a plain CSV export (Training Reports & Costs, My Training,
 * and any future one). Built on ExcelJS rather than the plain `xlsx`
 * package already used elsewhere in this app (reportExportService.ts) --
 * the free/npm `xlsx` (SheetJS Community Edition) build does not write
 * cell styles (fill colour, borders, bold, freeze panes), which every one
 * of these exports needs. `xlsx` itself is left untouched for its existing
 * unstyled multi-sheet exports; this is a separate, additive dependency
 * for exports that need real spreadsheet formatting.
 */

export type ExcelColumn = {
  header: string;
  /** Column width in Excel's character-width units. */
  width?: number;
  /** Applied to every data-row cell in this column, e.g. '#,##0.00' for ZAR. */
  numberFormat?: string;
};

export type ExcelSheetSpec = {
  /** Sheet tab name -- ExcelJS truncates/rejects over 31 chars, so keep these short. */
  name: string;
  /** Free-text lines above the header (company name/report title, FY/date range, "Generated by: ..."). One row each, a blank row is added automatically after them. */
  titleLines: string[];
  columns: ExcelColumn[];
  rows: Array<Array<string | number | null>>;
  /** Optional bold summary row appended after the data rows (e.g. TOTAL). */
  totalsRow?: Array<string | number | null>;
};

const TEAL_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0B9E75' } };
const TOTALS_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE1F5EE' } };
const ALT_ROW_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F5F5' } };
const THIN_BORDER: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: 'FFD0D0D0' } },
  left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
  bottom: { style: 'thin', color: { argb: 'FFD0D0D0' } },
  right: { style: 'thin', color: { argb: 'FFD0D0D0' } }
};

function autoFitWidth(header: string, values: Array<string | number | null>, explicit?: number): number {
  if (explicit) return explicit;
  const longest = values.reduce<number>((max, v) => Math.max(max, String(v ?? '').length), header.length);
  return Math.min(50, Math.max(10, longest + 2));
}

function addSheet(workbook: ExcelJS.Workbook, spec: ExcelSheetSpec): void {
  const sheet = workbook.addWorksheet(spec.name.slice(0, 31) || 'Sheet1');

  for (const line of spec.titleLines) {
    const row = sheet.addRow([line]);
    row.font = { bold: true, size: line === spec.titleLines[0] ? 13 : 10 };
  }
  sheet.addRow([]); // blank separator row

  const headerRowNumber = spec.titleLines.length + 2;
  const headerRow = sheet.addRow(spec.columns.map((c) => c.header));
  headerRow.height = 20;
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = TEAL_FILL;
    cell.border = THIN_BORDER;
    cell.alignment = { vertical: 'middle' };
  });

  spec.rows.forEach((row, rowIndex) => {
    const excelRow = sheet.addRow(row);
    const isAlt = rowIndex % 2 === 1;
    excelRow.eachCell((cell, colNumber) => {
      cell.border = THIN_BORDER;
      if (isAlt) cell.fill = ALT_ROW_FILL;
      const fmt = spec.columns[colNumber - 1]?.numberFormat;
      if (fmt) cell.numFmt = fmt;
    });
  });

  if (spec.totalsRow) {
    const totalsExcelRow = sheet.addRow(spec.totalsRow);
    totalsExcelRow.eachCell((cell, colNumber) => {
      cell.font = { bold: true };
      cell.fill = TOTALS_FILL;
      cell.border = THIN_BORDER;
      const fmt = spec.columns[colNumber - 1]?.numberFormat;
      if (fmt) cell.numFmt = fmt;
    });
  }

  sheet.columns = spec.columns.map((col, i) => ({
    width: autoFitWidth(
      col.header,
      [...spec.rows.map((r) => r[i]), ...(spec.totalsRow ? [spec.totalsRow[i]] : [])],
      col.width
    )
  }));

  // Freeze the header row (and everything above it) so it stays visible on scroll.
  sheet.views = [{ state: 'frozen', ySplit: headerRowNumber }];
}

export async function downloadStyledExcelWorkbook(sheets: ExcelSheetSpec[], filename: string): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Safe Cloud Africa';
  workbook.created = new Date();
  for (const sheet of sheets) addSheet(workbook, sheet);

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
