import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { QualityNcr } from '../models/entities';
import { downloadPdfReport, drawPdfCoverWithLogo } from './reportExportService';

export async function exportNcrListPdf(input: {
  ncrs: QualityNcr[];
  companyName: string;
  generatedBy: string;
  logoUrl?: string | null;
  filename?: string;
}): Promise<void> {
  const safeOrg = input.companyName.replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'safecloudafrica';
  const filename = input.filename ?? `${safeOrg}-ncrs-${new Date().toISOString().slice(0, 10)}.pdf`;
  const metaLines = [
    `Company: ${input.companyName}`,
    `Generated by: ${input.generatedBy}`,
    `Generated at: ${new Date().toISOString()}`,
    `Records: ${input.ncrs.length}`
  ];
  const rows = input.ncrs.map((ncr) => ({
    nc_number: ncr.nc_number ?? '',
    title: ncr.title,
    status: ncr.status,
    severity: ncr.severity,
    location: ncr.location ?? '',
    process: ncr.process_involved ?? '',
    source: (ncr as { source_entity_type?: string }).source_entity_type ?? '',
    occurrence_date: ncr.occurrence_date ?? '',
    due_date: ncr.corrective_action_due_date ?? ''
  }));

  await downloadPdfReport(
    filename,
    `${input.companyName} — NCR Register`,
    rows,
    metaLines,
    { headerColor: [15, 118, 110], logoUrl: input.logoUrl }
  );
}

export async function exportNcrDetailPdf(input: {
  ncr: QualityNcr;
  companyName: string;
  generatedBy: string;
  logoUrl?: string | null;
  filename?: string;
}): Promise<Blob> {
  const { ncr } = input;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  const subtitle = ncr.nc_number ? `${ncr.nc_number} — ${ncr.title}` : ncr.title;
  let y = await drawPdfCoverWithLogo(doc, {
    title: 'Non-Conformance Report',
    subtitle,
    companyName: input.companyName,
    generatedBy: input.generatedBy,
    logoUrl: input.logoUrl
  });

  const detailRows: Array<[string, string]> = [
    ['Status', ncr.status],
    ['Severity', ncr.severity],
    ['Occurrence date', ncr.occurrence_date ? String(ncr.occurrence_date).slice(0, 10) : '—'],
    ['Location', ncr.location ?? '—'],
    ['Process', ncr.process_involved ?? '—'],
    ['Activity', ncr.activity_involved ?? '—'],
    ['Linked requirement', ncr.linked_requirement ?? '—'],
    ['Risk classification', ncr.risk_classification ?? ncr.risk_rating ?? '—'],
    ['Root cause', ncr.root_cause ?? '—'],
    ['Corrective action', ncr.corrective_action ?? '—'],
    ['Due date', ncr.corrective_action_due_date ? String(ncr.corrective_action_due_date).slice(0, 10) : '—'],
    ['Manager sign-off', ncr.manager_signoff_user_id ? 'Yes' : 'No'],
    ['Auditor verified', ncr.auditor_verify_user_id ? 'Yes' : 'No']
  ];

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('NCR details', 40, y);
  y += 16;

  autoTable(doc, {
    startY: y,
    body: detailRows,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 4, overflow: 'linebreak' },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 130 },
      1: { cellWidth: pageWidth - 210 }
    }
  });

  let nextY = ((doc as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? y) + 20;
  if (ncr.description?.trim()) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Description', 40, nextY);
    nextY += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(ncr.description.trim(), pageWidth - 80);
    doc.text(lines, 40, nextY);
    nextY += lines.length * 12 + 12;
  }

  const evidenceBefore = (ncr.evidence_before ?? []).length;
  const evidenceAfter = (ncr.evidence_after ?? []).length;
  autoTable(doc, {
    startY: nextY,
    head: [['Evidence type', 'Count']],
    body: [
      ['Before (issue)', String(evidenceBefore)],
      ['After (closure)', String(evidenceAfter)]
    ],
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255 }
  });

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - 80, doc.internal.pageSize.getHeight() - 20);
  }

  return doc.output('blob');
}
